### GET request to get all countries
GET localhost:8080/api/v1/countries/
Accept: application/json

### GET request to get one country's data
GET localhost:8080/api/v1/countries/Iran
Accept: application/json

### Send POST request to register user
POST localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "username": "mahdi",
  "password": "pass"
}

