### GET request to get all countries
GET localhost:8080/api/v1/countries/
Accept: application/json

### GET request to get one country's data
GET localhost:8080/api/v1/countries/Iran
Accept: application/json

### Send POST request to register user
POST localhost:8080/api/v1/auth/users/register
Content-Type: application/json

{
  "username": "mahdi",
  "password": "pass"
}

### Send POST request to login user
POST localhost:8080/api/v1/auth/users/login
Content-Type: application/json

{
  "username": "mahdi",
  "password": "pass"
}

### Send PUT request to enable user
PUT localhost:8080/api/v1/auth/admin/users?username=mahdi&active=true
Authorization: Bearer {{auth_token}}

### Send GET request by admin to get all users
GET localhost:8080/api/v1/auth/admin/users
Authorization: Bearer {{auth_token}}

### Send GET request to get country's data
GET localhost:8080/api/v1/countries/poland
Authorization: Bearer {{auth_token}}

### Send POST request to create api token
POST localhost:8080/api/v1/user/api-tokens/
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "mahdi",
  "expirationDate": "2025-01-01T23:59:59Z"
}

